### ISSUE TITLE
typo on the homepage

### ISSUE THREAD

**Issue by oakmac** [lightning-viz/lightning-viz.github.io#3]
"visualiztions" --> "visualizations"

I would make a pull request to fix, but I'm not sure where this lives in the repo.

![lightning-homepage-visualizations-typo](https://cloud.githubusercontent.com/assets/98485/6582937/b11dc92c-c72e-11e4-9a44-0ae0d6ef0d9f.png)

**Comment by freeman-lab** [comment]
Thanks for catching @oakmac !
